apiVersion: v1
kind: Service
metadata:
  name: node-mongo-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: node-mongo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
